# Generated by Django 6.0.2 on 2026-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('category', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Marketing', 'Marketing')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
