# Generated by Django 6.0.2 on 2026-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg'), ('drinks', 'drinks')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
