# Generated by Django 6.0.2 on 2026-04-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('disease', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
